config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :totals
  resources :values
  root 'home#index'

end

app/models/total.rb
class Total < ActiveRecord::Base
end

app/models/value.rb
class Value < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/totals_controller.rb
class TotalsController < ApplicationController
  before_action :set_total, only: [:show, :edit, :update, :destroy]

  # GET /totals
  # GET /totals.json
  def index
    @totals = Total.all
  end

  # GET /totals/1
  # GET /totals/1.json
  def show
  end

  # GET /totals/new
  def new
    @total = Total.new
  end

  # GET /totals/1/edit
  def edit
  end

  # POST /totals
  # POST /totals.json
  def create
    @total = Total.new(total_params)

    respond_to do |format|
      if @total.save
        format.html { redirect_to @total, notice: 'Total was successfully created.' }
        format.json { render :show, status: :created, location: @total }
      else
        format.html { render :new }
        format.json { render json: @total.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /totals/1
  # PATCH/PUT /totals/1.json
  def update
    respond_to do |format|
      if @total.update(total_params)
        format.html { redirect_to @total, notice: 'Total was successfully updated.' }
        format.json { render :show, status: :ok, location: @total }
      else
        format.html { render :edit }
        format.json { render json: @total.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /totals/1
  # DELETE /totals/1.json
  def destroy
    @total.destroy
    respond_to do |format|
      format.html { redirect_to totals_url, notice: 'Total was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_total
      @total = Total.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def total_params
      params.require(:total).permit(:total)
    end
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: [:show, :edit, :update, :destroy]

  # GET /values
  # GET /values.json
  def index
    @values = Value.all
  end

  # GET /values/1
  # GET /values/1.json
  def show
  end

  # GET /values/new
  def new
    @value = Value.new
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values
  # POST /values.json
  def create
    @value = Value.new(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to @value, notice: 'Value was successfully created.' }
        format.json { render :show, status: :created, location: @value }
      else
        format.html { render :new }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1
  # PATCH/PUT /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to @value, notice: 'Value was successfully updated.' }
        format.json { render :show, status: :ok, location: @value }
      else
        format.html { render :edit }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1
  # DELETE /values/1.json
  def destroy
    @value.destroy
    respond_to do |format|
      format.html { redirect_to values_url, notice: 'Value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def value_params
      params.require(:value).permit(:value1, :value2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/home/index.html.erb
<h1>Inicio</h1>

<ul>
	<li><a href="/values">Valores</a></li>
	<li><a href="/totals">total</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TesteRegraDeNegocio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="/">Inicio</a>
<%= yield %>

</body>
</html>

app/views/totals/_form.html.erb
<%= form_for(@total) do |f| %>
  <% if @total.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@total.errors.count, "error") %> prohibited this total from being saved:</h2>

      <ul>
      <% @total.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/totals/edit.html.erb
<h1>Editing Total</h1>

<%= render 'form' %>

<%= link_to 'Show', @total %> |
<%= link_to 'Back', totals_path %>

app/views/totals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Totals</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @totals.each do |total| %>
      <tr>
        <td><%= total.total %></td>
        <td><%= link_to 'Show', total %></td>
        <td><%= link_to 'Edit', edit_total_path(total) %></td>
        <td><%= link_to 'Destroy', total, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Total', new_total_path %>

app/views/totals/new.html.erb
<h1>New Total</h1>

<%= render 'form' %>

<%= link_to 'Back', totals_path %>

app/views/totals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @total.total %>
</p>

<%= link_to 'Edit', edit_total_path(@total) %> |
<%= link_to 'Back', totals_path %>

app/views/values/_form.html.erb
<%= form_for(@value) do |f| %>
  <% if @value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
      <% @value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value1 %><br>
    <%= f.text_field :value1 %>
  </div>
  <div class="field">
    <%= f.label :value2 %><br>
    <%= f.text_field :value2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/values/edit.html.erb
<h1>Editing Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app/views/values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Values</h1>

<table>
  <thead>
    <tr>
      <th>Value1</th>
      <th>Value2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @values.each do |value| %>
      <tr>
        <td><%= value.value1 %></td>
        <td><%= value.value2 %></td>
        <td><%= link_to 'Show', value %></td>
        <td><%= link_to 'Edit', edit_value_path(value) %></td>
        <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value', new_value_path %>

app/views/values/new.html.erb
<h1>New Value</h1>

<%= render 'form' %>

<%= link_to 'Back', values_path %>

app/views/values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value1:</strong>
  <%= @value.value1 %>
</p>

<p>
  <strong>Value2:</strong>
  <%= @value.value2 %>
</p>

<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>